VisionCameraScreen: - display scanned results and time taken on SingleScanners screen - ensure frame processor runs only when the screen is mounted - grab scanned barcodes, merge them to route params then navigate to SingleScanners screen - ensure that the flash is set off after navigation to another screen or if the AppState is not active
-- still get the esoteric view not found error i.e
```Error: Exception in HostFunction:
com.mrousavy.camera.ViewNotFoundError: [system/view-not-found] The given
view (ID 2215) was not found in the view manager.```
I manage to get past this by triggering a save while on
VisionCameraScreen, in dev mode